#!/bin/bash

echo "If a terminal doesn't open automatically, check X11 settings or"
echo "find output .out file located in /data/var/jobs/recon-all/"${1}.out
x-terminal-emulator -e 'tail -F /data/var/jobs/recon-all/'${1}.out
sleep 1
